version: "3.8"

services:

  pgdb:
    container_name: pgdb
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - pgdb
  gateway:
    container_name: gateway
    build: .
    command: bash -c "alembic upgrade head && cd gateway && uvicorn main:app --host 0.0.0.0 --port ${GATEWAY_PORT}"
    volumes:
      - .:/app
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    restart: always
    depends_on:
      - pgdb