run:
	docker-compose up
build:
	docker-compose up --build
alembic_init:
	alembic init alembic
alembic_migration:
	alembic revision -m "init"
alembic_migrate:
	alembic upgrade heads
alembi_autogenarate_migration:
	alembic revision --autogenerate -m ""
