"""create mock table

Revision ID: 0bf6b4e783ef
Revises: 968060135d36
Create Date: 2022-03-19 09:21:16.425721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf6b4e783ef'
down_revision = '968060135d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('reponse', sa.String(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['api.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_id'), 'mock', ['id'], unique=False)
    op.alter_column('api', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'api', ['path'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api', type_='unique')
    op.alter_column('api', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_mock_id'), table_name='mock')
    op.drop_table('mock')
    # ### end Alembic commands ###
