"""mock dodified

Revision ID: 5fdb3011e59b
Revises: 0bf6b4e783ef
Create Date: 2022-03-19 16:29:33.229282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fdb3011e59b'
down_revision = '0bf6b4e783ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mock', sa.Column('path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mock', 'path')
    # ### end Alembic commands ###
